In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print("Numpy Array")
print(arr)
print(arr[3])
print(arr[-3])
print(arr[2:3])
print(arr[-3:])
print(arr+3)
print(arr-3)
print(arr*3)
print(arr/2)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(arr.reshape(1,5))

Numpy Array
[1 2 3 4 5]
4
3
[3]
[3 4 5]
[4 5 6 7 8]
[-2 -1  0  1  2]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
15
3.0
5
1
[[1 2 3 4 5]]

In [3]:
import pandas as pd
data={
    "Name":["Asha","Ravi","Meera","Karan"],
    "Marks":[88,91,72,65],
    "Branch":["CSE","ECE","CSE","ISE"]
    }
df=pd.DataFrame(data)
print(df)

    Name  Marks Branch
0   Asha     88    CSE
1   Ravi     91    ECE
2  Meera     72    CSE
3  Karan     65    ISE

In [4]:
df.head()

    Name  Marks Branch
0   Asha     88    CSE
1   Ravi     91    ECE
2  Meera     72    CSE
3  Karan     65    ISE

In [5]:
df.tail()

    Name  Marks Branch
0   Asha     88    CSE
1   Ravi     91    ECE
2  Meera     72    CSE
3  Karan     65    ISE

In [6]:
print(df["Name"])

0     Asha
1     Ravi
2    Meera
3    Karan
Name: Name, dtype: str

In [7]:
print(df.shape)

(4, 3)

In [8]:
df.iloc[2]

Name      Meera
Marks        72
Branch      CSE
Name: 2, dtype: object

In [9]:
print(df.loc[0])

Name      Asha
Marks       88
Branch     CSE
Name: 0, dtype: object